### ISSUE TITLE
Spider web works before the infection

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#102]
Steps to reproduce
1. The whole process needs to happen between the round start and the infection start
2. Get spider as a zombie
3. Try to hook a human, it will not work (because the infection has not started yet)
4. Hook a hookable tile, jump so that the human crossed the hook

Expected: same as step 3, the human should not get hooked
Observed: human gets hooked for 3 seconds

The good thing is that although the human gets hooked, they do not get any damage.

**Comment by Kaffeine** [comment]
Fixed by commit 868f4d4ba4e290fe8c007730d762a06d6e97bae8, thanks!
