### ISSUE TITLE
Add info about turrets to the hero help page (/help hero)

### ISSUE THREAD

**Issue by Kaffeine** [infclass/teeworlds-infclassR#21]

**Comment by Intramint** [comment]
~~ Hero ~~
The Hero has a shotgun, a laser rifle and a grenade launcher.

The Hero has to find a flag only visible to them. Stand still to be pointed towards it. The flag gifts a health point, 4 armor and full ammo to all humans. It fully heals the Hero and it can grant a turret which you can place down with the hammer.
The gift to all humans is only applied when the flag is surrounded by hearts and armor.

The Hero cannot be healed by a Medic, but it can withstand a hit from an infected.

**Comment by Kaffeine** [comment]
Closed by commit 27ddd384e0e45bc54541d3e6dc40b2b6d79e7157.
@Intramint thanks!
