### ISSUE TITLE
Mercenary grenades make no effect

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#27]
Version: currently deployed to Zombies' Cafe

Steps to reproduce:
1. 1 mercenary, 1 zombie
2. The mercenary shoots grenades at zombie and explodes them

Expected:
The zombie loses 1 hp per second for 8 seconds

Current:
The zombie shows "annoyed" emotion and loses no hp.

**Comment by Kaffeine** [comment]
Oh. Thank you for the issue.

**Comment by Kaffeine** [comment]
Bisected to a commit... I'll fix it in some minutes.

**Comment by Kaffeine** [comment]
Fixed. Thank you!
The server 'll be updated as soon as everyone left.

**Comment by Kaffeine** [comment]
Fixed. Thank you!
The server 'll be updated as soon as everyone left.
