### ISSUE TITLE
electrician makes damage for zombies in infection zone

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#28]
Steps to reproduce:
1. 1 electrician, 1 zombie
2. The electrician places a box not far from a zombie spawn, shoots the zombie
3. The zombie jumps into the infection zone
4. The electrician hits the hammer within 1 second
OR
4. The zombie goes out of range within 1 second inside the infection zone

Expected:
1-second invincibility is honored and the zombie does not die

Current:
Zombie dies even if jumped into the zone within 1 second

**Comment by Kaffeine** [comment]
Fixed as "Expected": the link is kept but the target does not die on discharge anymore.

Gracias!

**Comment by Kaffeine** [comment]
Actually fixed. Thx again.
