### ISSUE TITLE
electrician kills are not shared with ninja

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#29]
Steps to reproduce:
1. 1 zombie, 1 electrician, 1 ninja
2. The electrician creates a box
2. The ninja stuns the zombie
3. The electrician links the zombie and kills it

Expected:
A frag if given to both electrician and ninja

Current:
A frag is given only to the electrician

**Comment by Kaffeine** [comment]
Fixed & deployed. Thank you!
