### ISSUE TITLE
Broadcast "Class disabled" info if the class is not choosable

### ISSUE THREAD

**Issue by Intramint** [infclass/teeworlds-infclassR#35]
Hovering over a class on the wheel selector that cannot be chosen shall broadcast info on the reason behind the inability. Broadcast "Need at least 'inf_min_players_for_engineer' players" if there isn't enough players for Engineer. Broadcast "Class disabled" for any other reason e.g. classes in development like Electrician.

**Comment by Kaffeine** [comment]
8f622e1d2f9eb7b6041f603f0e0484f826e44d54
