### ISSUE TITLE
Shotgun bullets are broken for Specs

### ISSUE THREAD

**Issue by Kaffeine** [infclass/teeworlds-infclassR#38]

**Comment by Intramint** [comment]
this is a DDnet issue, not infclass related. same thing happens on all servers

**Comment by Kaffeine** [comment]
> this is a DDnet issue, not infclass related. same thing happens on all servers

Do you know if this also affects the official Teeworlds? E.g. vanilla 0.6.5 client with vanilla 0.6.5 (ctf/dm) server?

**Comment by Kaffeine** [comment]
![image](https://user-images.githubusercontent.com/374839/157225950-c7ee31db-57be-41ec-80f6-b50f51576b03.png)

Seems to be a bug in default tuning setup. The fix is on its way to DDNet.

**Comment by Kaffeine** [comment]
PR for the upstream: https://github.com/ddnet/ddnet/pull/4795

**Comment by Kaffeine** [comment]
Fixed in the upstream and InfClass client
