### ISSUE TITLE
Improve map rotation mechanism

### ISSUE THREAD

**Issue by Kaffeine** [infclass/teeworlds-infclassR#39]
Right now the rotation goes through a list of maps. The maps that does not meet requirements (right now we have only `minplayers` requirement) are skipped and won't be suggested until all the other maps got their chance.

One of the possible solutions is to keep the list of skipped maps and try them first.
E.g. if a map was not activated because of the low players count, it should still be activated on the next rotation if the conditions now met.

Probably we need even better mechanism.

Please discuss! @InfectionDust/scientists, @InfectionDust/engineers.

**Comment by Intramint** [comment]
On a server start, it starts at 1.
1. WHILE a threshold for the upcoming map isn't reached, put it at the end of the deck. if there aren't any viable maps in the deck go to step 4
2. draw the next map and then discard it
3. go to step 5.
4. randomise map order (including big maps)
5. if a threshold for a map is reached, put that map as the next draw (put the one which requires less players at the top first if 2+ are viable during a reshuffle. then the bigger one will be next)

advantages:
- maps have a random order but each will played once per map rotation (or 0 times for bigger maps if the threshold isn't passed)
- a map with a minimum player count criteria will be chosen if there are enough players right before the map switch
- big maps will still be played only once per rotation even if the player count threshold is passed multiple times during the rotation
- big maps will still be prioritized even if it's the beginning of the rotation

**Comment by Kaffeine** [comment]
Closed by 92728fb50798374e1d197cbb482644f786d4ffbe
