### ISSUE TITLE
Improve /help pages

### ISSUE THREAD

**Issue by Intramint** [infclass/teeworlds-infclassR#46]
- [x] /help game
**Change** "The goal for humans is to survive until the army clean the map."
**Into** "The goal for humans is to survive until the army cleans the map."

- [x] /help engineer
**Change** "When an infected touch the wall, he dies."
**Into** "When an infected touches the wall, it dies."

- [x] /help soldier
**Remove** "A lucky Soldier, devoted to killing zombies, can get a bonus - stunning grenades."

- [x] /help scientist
**Change** "Scientist has also grenades that teleport him."
**Into** "Scientist also has grenades that teleport them."
**Change** "Additionally scientist can place white holes with the laser rifle. Further information on /help whitehole"
**Into** "A lucky Scientist devoted to killing can get a white hole that sucks infected in which can be placed with the laser rifle"
**Remove** /help whitehole

- [x] /help biologist
**Change** "The biologist has a shotgun with bouncing bullets and can create a spring laser trap by shooting with the rifle."
**Into** "The Biologist has a shotgun with bouncing bullets and can create a spring laser trap by shooting with the laser rifle."

- [x] /help looper
**Change** "The looper has a laser wall that slows down zombies and a low-range-laser-pistol."
**Into** "The Looper has a laser wall that slows down infected and a low-range laser rifle with a high fire rate"
**Remove** "A lucky Looper, devoted to killing zombies, can get a bonus - stunning grenades."

- [x] /help medic
**Change** "Grenades with medicine give armor to everybody in their range, including heroes and medic themself"
**Into** "Grenades with medicine give armor to everybody in their range, including Heroes and  the Medic themself"
**Change** "Laser revives infected zombies, but at great cost - 17 hp and armor.
**Into** "Laser rifle revives the infected, but at the cost of 17 hp and armor."
**Change** "Medic has also a powerful shotgun that can pullback infected."
**Into** "Medic also has a powerful shotgun that can knock back infected."

- [x] /help ninja
**Change** "The Ninja can throw flash grenades that can freeze infected during three seconds."
**Into** "The Ninja can throw flash grenades that can freeze infected for three seconds"
**Change** "His hammer is replaced by a katana, allowing him to jump {int:NinjaJump} times before touching the ground."
**Into** "Their hammer is replaced with a katana, allowing them to dash {int:NinjaJump} times before touching the ground."
**Change** "Ninjas get special targets. For killing a target, extra points and abilities are awarded"
**Into** "Ninja gets special targets. For killing a target, extra points and abilities are awarded"

- [x] /help mercenary
**Change** "The Mercenaries fly in the air using their machine gun."
**Into** "The Mercenary can fly in the air using their machine gun."

- [x] /help sniper
**Change** "The Sniper can lock the position in air for 15 seconds with the hammer."
**Into** "The Sniper can lock the position in mid-air for 15 seconds with the hammer."
**Change** "Snipers can jump two times in air."
**Into** "Sniper can jump two times in the air."

- [x] /help smoker
**Change** "Smoker has a powerful hook that hurts human.
Their hook not only hurts humans, but also sucks their blood, restoring the smokers health."
**Into** "Smoker has a powerful hook that hurts humans and sucks their blood, restoring the Smoker's health."

- [x] /help hunter
**Change** "He can jump two times in air."
**Into** "It can jump two times in the air."

- [x] /help bat
**Change** "Bat can jump multiple times in air."
**Into** "Bat can jump infinitely in the air."
**Change** "It can also inflict 1 damage point per second by hooking humans.
Their hook not only hurts humans, but also sucks their blood, restoring the bats health.
**Into** "It can also inflict 1 damage point per second by hooking humans, which sucks their blood, restoring the Bat's health."

- [x] /help ghost
**Change** "He is invisible, except if a human is near him, if it takes a damage or if it use the hammer."
**Into** "It is invisible, unless a human is nearby, it takes damage or it uses the hammer."
**Change** "He can also inflict 1 damage point per second by hooking humans."
**Into** "It can also inflict 1 damage point per second by hooking humans."

- [x] /help spider
**Change** "When selecting any gun, the hook enter in web mode."
**Into** "When changing weapon, the hook enters web mode."
**Change** "Any human that touch a hook in web mode is automatically grabbed."
**Into** "Any human that touches a hook in web mode is automatically grabbed."
**Change** "The hook of the spider (in both mode) deal 1 damage point per second and can grab a human during 2 seconds."
**Into** "The hook (in both modes) inflicts 1 damage point per second and can grab a human for longer."

- [x] /help ghoul
**Change** "He can devour all that has died close to him, which makes him stronger, faster and more resistant."
**Into** "It can devour anything that has died nearby, which makes it stronger, faster and more resistant."
**Change** "Thereupon it digests the fodder bit by bit going back to the normal state, and besides, death bereaves him of the nourishment."
**Into** "It digests the fodder over time, going back to the normal state. Some nourishment is also lost on death."
**Add** "It can also inflict 1 damage point per second by hooking humans."

- [x] /help slug
**Change** "He can make the ground and walls toxic by spreading slime with the hammer."
**Into** "It can make the ground and walls toxic by spreading slime with the hammer."
**Change** "Touching the slime inflicts three damage points in three seconds on a human."
**Into** "Touching the slime inflicts 3 damage points in three seconds to a human."
**Add** "It can also inflict 1 damage point per second by hooking humans."

- [x] /help voodoo
**Change** "He does not die immediately when killed but instead enters Spirit mode and defies death for a brief span of time."
**Into** "It does not die immediately when killed but instead enters Spirit mode for a short time"
**Add** "It can also inflict 1 damage point per second by hooking humans."

- [x] /help undead
**Change** "Instead of dying, it freezes during 10 seconds."
**Into** "Instead of dying, it freezes for 10 seconds."
**Change** "If an infected heals him, the freeze effect disappear."
**Into** "If an infected heals it, the freeze effect disappears."
**Change** "He can also inflict 1 damage point per second by hooking humans."
**Into** "It can also inflict 1 damage point per second by hooking humans."

- [x] /help witch
**Change** "When an infected dies, it may re-spawn near witch."
**Into** "When an infected dies, it may respawn near the Witch."
**Remove** "Additionally a witch can place portals with the laser rifle. Further information on /help portals"
**Remove** /help portals

**Comment by Kaffeine** [comment]
Note: those main pages had translations for all 23 supported languages. The `data/languages/` files should follow the changes to keep translations working.

**Comment by Kaffeine** [comment]
<s>@Intramint info about the Looper grenade launcher is missing. I would appreciate if you add it.</s> nvm

**Comment by Kaffeine** [comment]
Done.
