### ISSUE TITLE
Hero does not add pistol ammo for ninja

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#48]
Steps to reproduce:
1. Ninja, hero
2. Ninja shoots pistol and uses all ammo
3. Hero finds a flag with gift

Expectation:
Ninja's pistol gets full ammo

Observed:
Ninja's pistol ammo still low

Pistol is typically used to discover ghosts or to make 1-hp-hits on almost-dead zombies, and might tip the balance into zombies side.

**Comment by Kaffeine** [comment]
IDK if this is a bug or a feature.
The flag does not give the gun ammo to any class except Mercenary (for mercs the gun is the primary weapon).
https://github.com/InfectionDust/teeworlds-infclassR/blob/production/src/game/server/infclass/entities/infccharacter.cpp#L2291-L2338

**Comment by Kaffeine** [comment]
The Gun ammo added to the Hero gift.

6508b256c8a28e2529f60eaba55ccb7d0d951ab7
