### ISSUE TITLE
infection by a player in the first 10 seconds should be impossible

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#56]
Currently, in a normal flow, n players become zombies on the 10th second of the game and start infecting. The first 10 seconds are "warm-up", with players building stuff and preparing for the battle. However, there are several ways to break this flow:

A player can jump into the infection zone in the first seconds, or kill themselves, and:
  1. start infecting before everyone is ready
  2. start hooking (and making dmg) before everyone is ready
  3. become a boomer, run close enough to the humans and get killed
  4. pull other players in the infection zone (even before they decided on their class)
  5. spill slime as a slug

There is some protection against that:
  1. If a player jumps into the infection zone, they get stunned for 3-4 seconds
  2. Hammer-infecting zombies (hunter, smoker, spider) do not infect until the game starts (but still produce force)

This protection is not enough at all and should be extended to cover all the ways allowing to infect early.

**Comment by Kaffeine** [comment]
:bulb:  We can use the "Love effect" for this.

**Comment by Kaffeine** [comment]
https://github.com/InfectionDust/teeworlds-infclassR/commit/5ca46cceb8bfe406ab060773c6cd48d029022bc1
