### ISSUE TITLE
rejoining from the spectators gives a different random class

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#57]
Steps to reproduce:
1. In the first second of the game pick a random class
2. Join spectators
3. Join humans ASAP again (before the first 10 seconds of the game)
4. Pick a random class again

Expected: the same class is assigned as before joining the spectators. This is fair, because choosing a random class grants a privilege - full armor.

Observes: another class is being granted

**Comment by Kaffeine** [comment]
Now the class is kept as-is. If you picked a class, you'll still have it after rejoining (with the same hp/armor). If didn't pick the class yet, you'll get back to the class menu.

**Comment by Kaffeine** [comment]
c89933178b130580a2c25467525faa9adc200846
