### ISSUE TITLE
spawn protection protects boomer from booming

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#64]
Steps to reproduce:
1. Become a boomer
2. Boom somewhere to die
3. After spawning, hammer fast while still in the infection zone

Expected: i boom when i hammer
Observed: i do not boom during protection time (`inf_spawn_protection_time`)
Server: `*** Git revision hash: v1.3.0-116-g5c4581387026`

Although benign in many cases, it can prevent the boomer from infecting on some maps, for example, on `infc_warehouse2`, where a human can be on top of the infection zone.

This issue is somewhat close to #62

**Comment by bretonium** [comment]
This might be a recent regression/fix, because i cannot reproduce it in `v1.3.0-68-gc5890fc9e78a`

**Comment by Kaffeine** [comment]
Fixed by commit c8cde1959314c5093c93c700f8a7fe39d8e11cbe.

Thanks @bretonium
