### ISSUE TITLE
New automatic infection leads to killing all zombies

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#69]
It might take some attempts to reproduce it; the bug does not happen every time
Steps to reproduce:
1. 5 players. 2 zombies (A and B), 3 humans
2. Zombie A quits -> 1 human gets infected

Expected:
Zombie B is not affected at all, the new zombie gets killed

Observed:
Sometimes zombie B gets killed by the server too

**Comment by Kaffeine** [comment]
https://github.com/InfectionDust/teeworlds-infclassR/commit/bdc616165746a644a379f6b62a702173e730d9bb
