### ISSUE TITLE
Boomfly leads to camera jumping for spectators

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#70]
Steps to reproduce:
1. 4 players: 1 spectator, 1 human, 1 boomer, 1 zombie
2. Spectator spectates any point of the map
3. Boomer boomflies a zombie

Expected: spectator's camera stays where the spectator left it, or on the player the spectator chose
Observed: spectator's camera jumps to the place of boomfly, or follows the player that has been boomflied. This happens even when i focus on specific player.

**Comment by Kaffeine** [comment]
Closed by commit https://github.com/InfectionDust/teeworlds-infclassR/commit/aea4e31c6b2a520bd20f2324ae633c45ed90b228
Thanks!
