### ISSUE TITLE
Hammering other zombies heals the healer fully

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#73]
Steps to reproduce:
1. 2 zombies, both have just spawned and have full health and 0 armor
2. Zombie A hammers zombie B

Expected:
Zombie B gets healed until they have full health and armor, which takes 3 hammer hits. Zombie A gets 3 armors for these 3 hits

Observed:
Zombie A gets 1 hp/armor for every hit they make, even after 3 hammer hits, regardless if the other zombie received or not any hp/armor
```
[2022-02-14 21:09:42][chat]: *** InfectionClass, by necropotame (version 0.6.4, 1.4.0_a5)
[2022-02-14 21:09:42][chat]: *** Server version from Feb  5 2022
[2022-02-14 21:09:42][chat]: *** Git revision hash: v1.3.1-225-g190ff650ab47
```

**Comment by Kaffeine** [comment]
Fixed (fixed up in the commit https://github.com/InfectionDust/teeworlds-infclassR/commit/6c9796cb5b64a909c5f30ac7e0873acf3e128989). Thanks!
