### ISSUE TITLE
Hero flag is not visible sometimes

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#77]
```
[2022-03-08 14:56:53][chat]: *** InfectionClass Mod. Version: 0.6.4, 1.4.0_a6
Client version 346c0a044
```
Steps to reproduce:
1. Server must be empty (0 players)
2. Connect to the server, pick hero
3. Skip map (i did it via votes)
4. Pick hero again
5. Look for the flag, stand near it, but do not take it
6. Disconnect (i closed the client with Alt+F4)
7. Connect again to the same server, it must be empty
8. Pick hero and look for the flag

Some steps might be unnecessary, i had no chance to test better.

Expected: the flag can be found, the pointer to the flag shows where it is
Observed: no flag anywhere, the pointer shows to an empty space

Bonus observation: if somebody joins after step 8 and becomes a zombie, the following broadcast is received by the hero:
```
[2022-03-08 15:05:31][broadcast]: Next flag in 356,166 mins, 19 secs
```

**Comment by Kaffeine** [comment]
Reproduced, thanks! :fire:

**Comment by Kaffeine** [comment]
https://github.com/InfectionDust/teeworlds-infclassR/commit/1583ea7cbf5e85061427e39270f0195fe5866561
