### ISSUE TITLE
feature: heat map

### ISSUE THREAD

**Issue by teoman002** [infclass/teeworlds-infclassR#8]
- begin to track minutes through server ticks after a round start
- when a death occurs, the position and time is saved in a struct, it also contains a color representation of the time.
- every death event adds a node to the linked list consisting of above mentioned struct type.
- later the linked list has to be saved, a different file name will be assigned for each map

**Comment by Kaffeine** [comment]
We don't have to do it in the server code. The data-analysis can and thus probably should be put outside.
It is typical for us to get events via console messages. Let's continue to use it.

We can extend the current messages (and add missing ones) so we'll have all the needed information in the log files. This way we'll have a minimum runtime overhead and able to reconstruct the events however we want.


> begin to track minutes through server ticks after a round start

We have round start message with timestamp (the first column []):
`[60474e66][game]: start round type='InfClassR' teamplay='0' id='1804289383'`

> When a death occurs, the position and time is saved in a struct, it also contains a color representation of the time.

We have the death timestamp and the only missing info is the position:
`[60474e75][game]: kill killer='breton' victim='jojo' weapon=2`

> every death event adds a node to the linked list consisting of above mentioned struct type.

No need for any further data structs, all events are already in the log file.

> later the linked list has to be saved, a different file name will be assigned for each map

A script can parse the log to get the idea about the map. I also consider an option to add the map to the `start round` message to simplify the parsing.

**Comment by Kaffeine** [comment]
We can use the same site (https://stats.resamvi.io/#/, https://github.com/InfectionDust/infclass-stats) to render heat maps or we can do some external scripts to rework the log into some SQL table and/or render graphs.

**Comment by teoman002** [comment]
- 75137a5 implemented the feature: console entry with `deathContext: mapName=%s aliveTime=%d position=%d,%d`
- configurable with a config_Var `InfLogDeathContext`
- is called at `CInfClassCharacter::Die()` and `CCharacter::TakeDamage()`
- not compilable right now, see discord message

**Comment by teoman002** [comment]
> We can use the same site (https://stats.resamvi.io/#/, https://github.com/InfectionDust/infclass-stats) to render heat maps

Yes, good idea. Python matplotlib can render 2d color maps with transparency: [heatmap examples](https://stackoverflow.com/questions/33282368/plotting-a-2d-heatmap-with-matplotlib)

**Comment by teoman002** [comment]
- 1a27caf solved the compiling bug
- implemented `CGameContext::logDeathContext(int ClientID)`
- message changed to `deathContext: mapName=%s lifetime=%d pos_x=%d pos_y=%d`
- called in `CInfClassCharacter::Die()` and `CCharacter::TakeDamage()`
- tested locally with 3 clients, no crashes, further testing required

**Comment by teoman002** [comment]
@Kaffeine Can you merge it?
I need the data for the future.

**Comment by Kaffeine** [comment]
> @Kaffeine Can you merge it?

I'll check the commits again and give you the feedback in a few hours.

**Comment by Kaffeine** [comment]
> @Kaffeine Can you merge it?

https://github.com/InfectionDust/teeworlds-infclassR/pull/47#pullrequestreview-738721282

**Comment by Kaffeine** [comment]
Totally outdated.
