### ISSUE TITLE
admin-mute does not capture /msg or /w

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#82]
Steps to reproduce:
1. As an admin, mute a player via the admin console (`mute <id> <time> <reason>`)
2. The muted player writes a private message to someone

Expected: the player cannot write anything
Observed: the player can still write private messages (via /w or /msg, not sure)

**Comment by Kaffeine** [comment]
Probably now they do (see 8dfc13eb2af49df4d152d3627d66c3fd33f2bb6d)
