### ISSUE TITLE
Dummies are no longer blocked

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#86]
Steps to reproduce:

1. Join Zombie's Cafe
2. Add a dummy

Expected: dummy cannot join
Observed: dummy joins

Can be reproduced only on Zombie's Cafe, not on 1.4.2.
I could reproduce with the Infclass Client, and did not try with vanilla ddnet

**Comment by Kaffeine** [comment]
Reproducible after https://github.com/InfectionDust/teeworlds-infclassR/commit/54455d1abcd93aea54ce40dfa1b6b5eb859d96c4
Probably I'll revert it but I want to check other options at first.

**Comment by Kaffeine** [comment]
Fixed
