### ISSUE TITLE
Engineer's wall does not flicker before disappearing

### ISSUE THREAD

**Issue by bretonium** [infclass/teeworlds-infclassR#89]
version: `1.5.0_a7`

Steps to reproduce: take an engineer, place a wall

Expected: when the wall TTL is between 0 and 10 seconds, the wall flickers, becoming thinner, to signal about it's status
Observed: wall thickness does not change at all, as it was in the previous versions

**Comment by Kaffeine** [comment]
Fixed by commit 8d8ac5a15610a16a4c9174e426b7a82cde705875

**Comment by Kaffeine** [comment]
@bretonium thank you!
