### ISSUE TITLE
Survival commands don't exist

### ISSUE THREAD

**Issue by Hanuko33** [infclass/teeworlds-infclassR#91]
they just don't exist anywhere, in config, in rcon (f2)...
I buildt it on linux from source with cmake and make.
It just says "command not found"

**Comment by Kaffeine** [comment]
Correct. I'm not ready to publish the bots just yet. Maybe I'll publish them eventually (not in the next release though).

**Comment by Kaffeine** [comment]
Closed as "Not a bug". Survival rounds are intentionally not available yet.
